import { registerResource } from "@saintrelion/data-access-layer";

registerResource({
  name: "activitylog",
  endpoint: "activitylog/",
  store: "ActivityLog",
});

export const mockActivityLogs = [
  {
    id: 2,
    timestamp: "2026-01-08 14:28:42",
    user: "Maria Santos",
    userRole: "Client",
    action: "Cash Payment Submitted",
    category: "billing",
    description: "Cash payment received ₱999 - Plan: Basic 25Mbps. Change: ₱1",
    ipAddress: "203.177.42.89",
    status: "success",
    metadata: {
      amount: 999,
      paymentMethod: "Cash",
      planName: "Basic 25Mbps",
    },
  },
  {
    id: 3,
    timestamp: "2026-01-08 14:15:33",
    user: "Admin Juan",
    userRole: "Admin",
    action: "Subscription Updated",
    category: "subscription",
    description:
      "Upgraded Carlos Mendoza from Basic 25Mbps to Premium 100Mbps - Next billing: Jan 15, 2026",
    ipAddress: "192.168.1.100",
    status: "success",
    metadata: { planName: "Premium 100Mbps" },
  },
  {
    id: 4,
    timestamp: "2026-01-08 13:58:21",
    user: "System Auto",
    userRole: "System",
    action: "Critical Ticket Created",
    category: "support",
    description:
      "Auto-generated ticket #1045 for Pedro Reyes - Issue: No Connection | Priority: Critical",
    ipAddress: "127.0.0.1",
    status: "warning",
    metadata: { ticketId: "1045", priority: "Critical" },
  },
  {
    id: 5,
    timestamp: "2026-01-08 13:45:10",
    user: "Lisa Tan",
    userRole: "Client",
    action: "Login Failed",
    category: "security",
    description: "Failed login attempt - Incorrect password (3rd attempt)",
    ipAddress: "180.190.45.12",
    status: "failed",
  },
  {
    id: 6,
    timestamp: "2026-01-08 13:30:05",
    user: "Admin Maria",
    userRole: "Admin",
    action: "Billing Settings Modified",
    category: "system",
    description: "Updated due date grace period from 5 days to 7 days",
    ipAddress: "192.168.1.101",
    status: "success",
  },
  {
    id: 7,
    timestamp: "2026-01-08 13:12:44",
    user: "Robert Santos",
    userRole: "Client",
    action: "Plan Change Requested",
    category: "subscription",
    description:
      "Requested downgrade from Premium 100Mbps to Standard 50Mbps - Effective: Next billing cycle",
    ipAddress: "202.90.143.77",
    status: "warning",
    metadata: { planName: "Standard 50Mbps" },
  },
  {
    id: 8,
    timestamp: "2026-01-08 12:55:33",
    user: "Admin Juan",
    userRole: "Admin",
    action: "Account Suspended",
    category: "user_management",
    description:
      "Suspended Patricia Flores account - Reason: Overdue payment (45 days)",
    ipAddress: "192.168.1.100",
    status: "success",
  },
  {
    id: 9,
    timestamp: "2026-01-08 12:40:22",
    user: "Michael Torres",
    userRole: "Client",
    action: "Support Ticket Opened",
    category: "support",
    description:
      "Created ticket #1046 - Issue: Slow Browsing | Priority: High | Assigned: Tech-02",
    ipAddress: "112.200.55.34",
    status: "success",
    metadata: { ticketId: "1046", priority: "High" },
  },
  {
    id: 10,
    timestamp: "2026-01-08 12:25:11",
    user: "Jennifer Lopez",
    userRole: "Client",
    action: "Bank Transfer Verified",
    category: "billing",
    description:
      "Bank transfer payment ₱1,200 verified - Ref: BT20260108125 - Plan: Standard 50Mbps",
    ipAddress: "124.105.88.21",
    status: "success",
    metadata: {
      amount: 1200,
      paymentMethod: "Bank Transfer",
      planName: "Standard 50Mbps",
    },
  },
  {
    id: 11,
    timestamp: "2026-01-08 11:58:00",
    user: "Admin Maria",
    userRole: "Admin",
    action: "Monthly Report Generated",
    category: "reports",
    description:
      "Generated December 2025 revenue report - Total: ₱338,000 | Active subscribers: 1,175",
    ipAddress: "192.168.1.101",
    status: "success",
  },
  {
    id: 12,
    timestamp: "2026-01-08 11:42:15",
    user: "David Reyes",
    userRole: "Client",
    action: "Account Details Updated",
    category: "user_management",
    description:
      "Updated contact info - New phone: +63 917 123 4567 | Email: david.reyes@email.com",
    ipAddress: "210.213.77.99",
    status: "success",
  },
  {
    id: 13,
    timestamp: "2026-01-08 11:20:30",
    user: "System Auto",
    userRole: "System",
    action: "Database Backup",
    category: "system",
    description:
      "Daily automated database backup completed - Size: 2.3GB | Duration: 8 minutes",
    ipAddress: "127.0.0.1",
    status: "success",
  },
  {
    id: 14,
    timestamp: "2026-01-08 10:55:45",
    user: "Angela Martinez",
    userRole: "Client",
    action: "Mobile Login",
    category: "security",
    description: "Successful login from Android device - Location: Makati City",
    ipAddress: "175.176.88.54",
    status: "success",
  },
  {
    id: 15,
    timestamp: "2026-01-08 10:30:12",
    user: "Admin Juan",
    userRole: "Admin",
    action: "New Subscriber Added",
    category: "user_management",
    description:
      "Created account for Christopher Lee - Plan: Basic 25Mbps | Installation: Jan 12, 2026",
    ipAddress: "192.168.1.100",
    status: "success",
    metadata: { planName: "Basic 25Mbps" },
  },
  {
    id: 16,
    timestamp: "2026-01-08 10:15:33",
    user: "System Auto",
    userRole: "System",
    action: "Payment Failed",
    category: "billing",
    description:
      "Auto-debit failed for Michelle Kim - Amount: ₱1,500 | Reason: Insufficient funds",
    ipAddress: "127.0.0.1",
    status: "failed",
    metadata: { amount: 1500, paymentMethod: "Auto-debit" },
  },
  {
    id: 17,
    timestamp: "2026-01-08 09:45:22",
    user: "Admin Maria",
    userRole: "Admin",
    action: "Ticket Closed",
    category: "support",
    description:
      "Resolved and closed ticket #1032 for Ana Garcia - Issue: Billing Query | Resolution time: 2 hours",
    ipAddress: "192.168.1.101",
    status: "success",
    metadata: { ticketId: "1032", priority: "Medium" },
  },
  {
    id: 18,
    timestamp: "2026-01-08 09:20:11",
    user: "Daniel Cruz",
    userRole: "Client",
    action: "Invoice Downloaded",
    category: "billing",
    description:
      "Downloaded billing invoice for December 2025 - Amount: ₱1,500 (PDF)",
    ipAddress: "112.201.77.88",
    status: "success",
  },
  {
    id: 19,
    timestamp: "2026-01-08 08:55:00",
    user: "System Auto",
    userRole: "System",
    action: "Payment Reminders Sent",
    category: "billing",
    description:
      "Sent automated payment reminders to 23 subscribers - Due dates within 3 days",
    ipAddress: "127.0.0.1",
    status: "success",
  },
  {
    id: 20,
    timestamp: "2026-01-08 08:30:45",
    user: "Sarah Johnson",
    userRole: "Client",
    action: "Password Changed",
    category: "security",
    description:
      "Password reset completed via email verification - Session invalidated",
    ipAddress: "220.144.99.11",
    status: "success",
  },
  {
    id: 21,
    timestamp: "2026-01-07 23:45:30",
    user: "Admin Juan",
    userRole: "Admin",
    action: "Bulk Status Update",
    category: "user_management",
    description: "Suspended 8 accounts for overdue payments exceeding 30 days",
    ipAddress: "192.168.1.100",
    status: "success",
  },
  {
    id: 22,
    timestamp: "2026-01-07 22:30:15",
    user: "Jessica Brown",
    userRole: "Client",
    action: "GCash Payment",
    category: "billing",
    description:
      "GCash payment ₱1,899 processed - Ref: GC20260107223 - Plan: Premium 100Mbps",
    ipAddress: "175.222.111.33",
    status: "success",
    metadata: {
      amount: 1899,
      paymentMethod: "GCash",
      planName: "Premium 100Mbps",
    },
  },
  {
    id: 23,
    timestamp: "2026-01-07 21:15:00",
    user: "Admin Maria",
    userRole: "Admin",
    action: "Promo Code Created",
    category: "marketing",
    description:
      "Created promo code 'NEWYEAR2026' - 20% discount for new subscribers | Valid until: Jan 31, 2026",
    ipAddress: "192.168.1.101",
    status: "success",
  },
  {
    id: 24,
    timestamp: "2026-01-07 20:00:45",
    user: "James Anderson",
    userRole: "Client",
    action: "Installation Scheduled",
    category: "subscription",
    description:
      "Scheduled fiber installation - Date: Jan 10, 2026 | Time: 1:00 PM - 5:00 PM | Area: Quezon City",
    ipAddress: "203.177.88.44",
    status: "success",
  },
  {
    id: 25,
    timestamp: "2026-01-07 19:30:22",
    user: "System Auto",
    userRole: "System",
    action: "Ticket Auto-Escalated",
    category: "support",
    description:
      "Auto-escalated ticket #1040 - Unresolved for 48 hours | Priority upgraded: High → Critical",
    ipAddress: "127.0.0.1",
    status: "warning",
    metadata: { ticketId: "1040", priority: "Critical" },
  },
];
